SELECT NVL(EDITORIAL,'SIN EDITORIAL'), COUNT(*) AS CUENTA FROM LIBROS 
GROUP BY EDITORIAL ORDER BY CUENTA;  

SELECT * FROM LIBROS;

SELECT NVL(EDITORIAL,'SIN EDITORIAL'), COUNT(*) AS CUENTA FROM LIBROS
WHERE PRECIO IS NOT NULL GROUP BY EDITORIAL;

SELECT NVL(EDITORIAL,'SIN EDITORIAL'), COUNT(PRECIO) AS CUENTA FROM LIBROS
GROUP BY EDITORIAL;

SELECT * FROM LIBROS;

SELECT NVL(EDITORIAL,'SIN EDITORIAL'), MAX(PRECIO) AS MAXIMO, MIN(PRECIO) AS MINIMO
FROM LIBROS GROUP BY EDITORIAL;

SELECT NVL(EDITORIAL,'SIN EDITORIAL'),AVG(PRECIO) AS PRECIO_MEDIO FROM LIBROS
GROUP BY EDITORIAL;

SELECT NVL(EDITORIAL,'SIN EDITORIAL'), COUNT(*) FROM LIBROS
WHERE PRECIO < 30 GROUP BY EDITORIAL;
